### ISSUE TITLE
As a developer I want Chirp.CLI to utilize an external library for CSV IO, for better performance and less room for mistakes

### ISSUE THREAD

**Issue by torbjornjohannsen** [ITU-BDSA2024-GROUP-26/Chirp#4]
**User story**
Currently our Chirp.CLI program uses very highly coupled custom CSV-parsing. This is prone to errors, most likely not the most efficient way to do this, plus it hurts the extendability of our program(If we for instance wish to add a new form of data to chirps).

**Acceptance Criteria** 
- External library properly setup as a dependency of our .NET project
- Reading lines of CSV data and retrieving the different comma seperated values
- Writing new lines to the CSV file in the same format, that can later be read

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
