### ISSUE TITLE
As a developer I want to move the UI logic in Chirp.CLI into its own class, for lower coupling

### ISSUE THREAD

**Issue by T0rvadaL** [ITU-BDSA2024-GROUP-26/Chirp#5]
**User story**
As a developer I want to move the UI logic in Chirp.CLI into its own class, for lower coupling

**Acceptance Criteria**
- All UI logic is encapsulated in it's own class

**Comment by Player1mene** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
